spring.application.name=ShopBadminton

spring.application.name=ShopBadminton

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ShopBadminton;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.upload.dir=uploads/products
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

jwt.secret=day_la_chuoi_bi_mat_it_nhat_32_ky_tu_cho_HS256_ShopBadminton
jwt.expiration=86400000

server.port=8080